# ==========================================
# CONFIGURAÇÕES GLOBAIS
# ==========================================
spring.application.name=swiftway
spring.profiles.active=dev
server.port=8080

# Swagger/OpenAPI
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
swiftway.matching.raio-max-km=5000
